CESNET/netopeer2

server/tests/CMakeLists.txt
Just use a similar approach as server/CMakeLists.txt is already doing
rather than a hardcoded list of libraries.
=> cmake: fix tests' linking with libraries outside of a default path

cli/CMakeLists.txt
There's a good existing CMake module which makes this configuration
less special and more boring; it also makes Debian crossbuilds much
easier.
=> cmake: Switch to GNUInstallDirs

server/main.c
Netopeer2 should require `sysrepod` to be running. If it is not running, it will start it automatically and reconnect.
=> server CHANGE require sysrepod to be running

keystored/CMakeLists.txt
The correct dir doesn't live underneath /usr on a typical system, so it
should be specified as an absolute path like this.
=> cmake: Use absolute path for keystored's key directory

server/op_editconfig.c
repeat step:
1. Install the module of module.yang. It will success.
2. Use edit-config in netopeer2-cli using init.xml to config data. It will report OK.
3. Use edit-config in netopeer2-cli using modify.xml to config data. It will report error like this:
"message:  edit_get_move: memory allocation failed (Unknown error -8191)"
module.yang:
```
module UserByOrderTest{
namespace "urn:ietf:params:xml:ns:yang:userbyordertest";
prefix UserByOrderTest;
container root{
leaf-list ff{
type string;
ordered-by user;
}
}
}
```
init.xml:
```xml
<root xmlns="urn:ietf:params:xml:ns:yang:userbyordertest"
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
<ff>aa</ff>
<ff>bb</ff>
<ff>cc</ff>
</root>
```
modify.xml
```xml
<root xmlns="urn:ietf:params:xml:ns:yang:userbyordertest" …
```
=> fix edit-config using model with ordered-by user attr under leaf-list report error

server/operations.c
Hi,
This is a bugfix for default flag when executing `get` or `get-config`, the default flag of the new created root node sometimes does not be set correctly.
=> server BUGFIX set wrong default flag when get-config

server/op_copyconfig.c
Hi,
Netopeer2 will create default nodes when using copy-config, this request is used to fix it.
=> server BUGFIX skip default nodes when copy-config

server/ietf_netconf_server.c
TLS listen does not work because the enumeration with the xpath "/ietf-netconf-server:netconf-server/listen/endpoint[tls]/*".
=> TLS listen does not work with child enumeration xpath

server/ietf_netconf_server.c
insufficient arguments of ERR lead to crash.
Signed-off-by: Jimmy, Chun-Tsung Wang <jimmy.wang@zyxel.com.tw>
=> fix a crash issue

server/operations.c, server/tests/test_get.c
Hi,
Operation `get` with subtree filter will get wrong nodes if it has two content match nodes, of which the first matched and second not, this request is used to fix it. I also add a test case for this case.
=> server BUGFIX subtree filter error for two content match nodes

cli/commands.c
When the target of get-schema is not found, some device is replying some thing like:
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="100">
<data/>
</rpc-reply>
```
causing segment fault in netopeer2-cli. Add checking to fix this.
=> cli BUGFIX segfault when get-schema returns empty data

server/main.c, server/tests/config.h.in, server/tests/files/test-feature-consumer.yin, server/tests/files/test-feature.yin, server/tests/test_edit_get_config.c
`np2srv_init_schemas()` walks through schemas in the order they are returned from sysrepo via `np2srv_sr_list_schemas()` and attemps to enable features that sysrepo indicates are supposed to be enabled.
However, if a feature in schema `n` depends on a feature that is found in schema `n + 1` (or any subsequent schema, for that matter), enabling the feature in schema `n` will fail because the feature in schema `n + 1` has not yet been enabled.
The additional unit test included in this commit demonstrates the problem.
This commit implements a solution as follows:
1. When walking through the schemas returned from sysrepo, keep a list containing all the features that will need to be enabled.
2. Now walk through all the schemas attempting to enable the recorded features. Some features may fail …
=> Fix enabling a feature that depends on a feature in a subsequent schema

server/main.c, server/tests/config.h.in, server/tests/files/test-feature-a.yin, server/tests/files/test-feature-b.yin, server/tests/files/test-feature-c.yin, server/tests/test_edit_get_config.c
This is a follow-up to pull request #248, which fixed a problem enabling a feature that depended on a feature in a subsequent schema that had not yet been enabled.
The follow-up optimizations in commit 6cb1612 inadvertently changed the desired behavior, in that a feature dependency chain more than two features deep will no longer be enabled properly. The problem is that the `making_progress` loop in main.c line 876 is never entered.
This change should address the issue. I've also included a change to the original unit test from #248, so that the test now demonstrates a feature dependency chain three features deep, instead of the original test which was only two features deep and did not catch the issue above.
=> Fix longer feature dependency chains (see #248)

server/ietf_system.c
When modifying ietf-system/authentication/user items on other fields than authorized-key, there is an error:
```
Path "/ietf-system:system/authentication/user[name='root']/password" modified.
Internal error (.../server/ietf_system.c:79)
```
Since netopeer does not care about these fields, it should ignore them.
=> ietf_system: do not error on unsupported fields

server/CMakeLists.txt
If `/etc/ssh/ssh_host_rsa_key` is not found during the cmake config step, there is a fatal error which makes the build fail:
```
-- Server configuration off, default SSH host key will be used.
CMake Error at CMakeLists.txt:71 (message):
Host key "/etc/ssh/ssh_host_rsa_key" not found, rerun cmake and set
DEFAULT_HOST_KEY manually to point to an RSA SSH key.
```
`DEFAULT_HOST_KEY` is only a default path used at runtime when no other path is specified. If a file actually exists here, it will not be read during the build (moreover, the default path is only readable by root anyway, and building as root is considered bad).
The machine where the server will run is not necessarily the one where the build is done. If the file is not found at runtime, there will be an explicit error.
Do not check …
=> server: ignore if host key not found at build time

cli/CMakeLists.txt, keystored/CMakeLists.txt, server/CMakeLists.txt, server/tests/CMakeLists.txt, server/tests/test_close_session.c, server/tests/test_copy_config.c, server/tests/test_edit_get_config.c, server/tests/test_generic.c, server/tests/test_get.c, server/tests/test_kill.c, server/tests/test_notif.c, server/tests/test_un_lock.c
As usual, all build artefacts should go outside of the source tree.
=> cmake: Do not clutter up the source dir during build

cli/commands.c, cli/configuration.c
Hi,
I made some small add-ons in order to get "call home" using netopeer2-cli working with public key authentication. These changes were necessary because the keys added by "auth keys add ..." command were not used for the "call home" ssh connection;  only password / interactive authentication was possible.
Please have a look at it. 
Regards,
Frank
=> make auth keys settings accessible for call home

keystored/CMakeLists.txt, server/CMakeLists.txt
We're using Buildroot for generating images which run on many devices. Buildroot performs the build as a regular user, and therefore one cannot call `sysrepoctl` with options for specifying a particular owner of a module. The build also has no access to the target system's SSH keys (they are generated during the first boot).
This patch series adds two options which make this situation doable. With these in place, it's reasonably straightforward to use Buildroot's native facilities for enforcing correct permissions as well as using systemd's units for proper key management. Yay.
I'll send patches which add the entire NETCONF server stack to Buildroot once these changes hit a release.
=> Improve experience when cross-compiling (permissions, key management)

keystored/CMakeLists.txt, keystored/scripts/ssh-key-import.sh, server/CMakeLists.txt
Commit f9dafad added a method of overriding the heuristics for checking the existing openssh-style host key. This got accidentally removed in 0970cea. The use case is Buildroot and reducing the amount of stuff which has to run on the target system.
=> SSH key provisioning: followup fixes

server/stock_config.xml
- enable IPv6 sockets (which include also IPv4 addresses on modern
Linux)
- use more descriptive names of the configuration
- nuke the "test" prefixes
=> Better defaults for listening configuration

server/op_notifications.c
This commit fixes a race condition in which _sysrepo_ could begin replaying notifications (in another thread) before the flag was set on the session indicating that the session could receive notifications.
=> Fix issue where notification replay might lose notifications

keystored/keystored.c
As of https://github.com/sysrepo/sysrepo/pull/1177, we started seeing errors in sysrepo-plugin when setting the ietf-keystore algorithm parameter. 
Example snippet:
```<action xmlns="urn:ietf:params:xml:ns:yang:1">
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
<private-keys>
<generate-private-key>
<name>nc-server</name>
<algorithm xmlns:ks="urn:ietf:params:xml:ns:yang:ietf-keystore">ks:rsa</algorithm>
</generate-private-key>
</private-keys>
</keystore>
</action>
```
Error:
```
Generating EC private keys not supported yet.
```
After investigation, we found that after the change in https://github.com/sysrepo/sysrepo/pull/1177, sysrepo is now passing both the module name and the identityref value to sysrepo-plugin and the current code is expecting just the identityref value. …
=> Updating keystored logic to account for module name in addtion to identityref value

server/tests/test_edit_get_config.c
This is a unit test that demonstrates the problem logged in https://github.com/CESNET/libyang/issues/566.
It attempts to delete a leaf whose type is an integer. (The test will not pass until the issue in https://github.com/CESNET/libyang/issues/566 is resolved.)
=> Add unit test that deletes integer leaf

server/CMakeLists.txt, server/main.c
This pull request fixes an issue with actions from augments. Before this change, an action added by an augment would always be treated as "unimplemented", even if there is a subscriber for it downstream of sysrepo.
We've written integration tests that demonstrate the problem. The fix here will allow the failing test cases (see [CI results], lines 7278-7279 and [test source code]) to pass. (We did not add a unit test for this, as main.c isn't being tested in that context right now.)
[CI results]: https://travis-ci.org/ADTRAN/netopeer2-integration-tests/builds/413288159#L7278
[test source code]: https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/tests/test_action.py#L58
=> Fix issue with actions from augments

server/CMakeLists.txt, server/common.h, server/config.h.in, server/main.c
Fixes #304
This change results in a 3x to 4x speedup for unfiltered get requests (and for requests for the ietf-yang-library contents).
We now cache the results of the `ly_ctx_info(np2srv.ly_ctx)` call and save it in the `np2srv` global, to avoid repeating the call when it would just return the same data.
We update the cached value when necessary, namely, when a module or feature is changed.
Because the contents of the cache should change relatively infrequently, it seems worth it to pay the cost early instead of for every request.
=> Cache ly_ctx_info to improve get performance

server/tests/files/test-feature-c.yin
This changes a test model to add a default to a leaf inside a container. The change will cause `test_edit_delete1()` in `test_edit_get_config` to fail due to the unexpected empty `test-container`. This failure demonstrates #316 . (The test will fail until until the issue in #316 is resolved.)
=> Test model modification to add default to leaf

server/operations.c, server/tests/files/test-feature-c.yin
Fixes #316.
The previous fix in a9844e2 unfortunately only fixes the case where the container with the default child(ren) is at the top level of the tree. When there are containers with default child(ren) nested inside of other containers, all of the outer containers still do not have their default flag set correctly.
This is because when `lyd_insert_common()` re-evaluates the default flag, it correctly updates not only the direct parent but also all more distant ancestors:
```
if (clrdflt) {
/* remove the dflt flag from parents */
for (iter = parent; iter && iter->dflt; iter = iter->parent) {
iter->dflt = 0;
}
}
```
This commit uses the same idea as a9844e2, but instead of saving only the immediate parent's `dflt` flag, it counts the number of non-default ancestors. After any node is …
=> Fix nested containers with default children

server/operations.c, server/tests/test_edit_get_config.c
This commit fixes the use case for a `get` or `get-config` with a subtree filter containing nodes from more than one schema. This scenario worked correctly in older commits, but was broken by the optimizations in 6ab0617.
The problem was that if there was a `root` tree already populated when `op_sr2ly()` was called, `op_sr2ly()` would correctly construct a new subtree with the requested data, but the subtree would never be attached to the existing `root` tree, and was essentially orphaned. Only the first tree connected to `root` would ever be returned.
I fixed this by adding a call to `lyd_insert_after()` when a new top-level node was created but there was already data in `root`.
This commit includes a test case that demonstrates the problem. The test case will pass in commits prior to …
=> Fix multi-schema filtered get

server/log.c
Changes for syslog priority strings which was done for consistency to match the the sysrepo priority format in syslog messages.  The goal is to allow external filtering on combined syslog files.
=> Update syslog message priority format to match sysrepo

cli/commands.c, server/config.h.in, server/main.c, server/tests/config.h.in
In addition to SSH and TLS transport, add the support for UNIX
socket.
Related with this pull request in libnetconf2: https://github.com/CESNET/libnetconf2/pull/123
This pull request contains one patch for the server and one for the cli.
=> add support for unix socket transport

server/integration-tests/Makefile
We had an issue where some of our automation environments could not execute the integration tests with docker run with the -t command, since it was not a TTY. So we have changed it to check if the environment is a TTY and if it is not then it will execute without it.
=> Fix docker run without TTY in automation environments

server/main.c, server/tests/test_kill.c
A memory leak reg. nc-poll-sessions has been detected during shutting down netopeer2-server. This PR provides test case and solution.
Regards,
Frank
=> close memory leak (test case + solution)

server/tests/CMakeLists.txt, server/tests/test_close_session.c, server/tests/test_copy_config.c, server/tests/test_delete_config.c, server/tests/test_edit_get_config.c, server/tests/test_generic.c, server/tests/test_get.c, server/tests/test_kill.c, server/tests/test_notif.c, server/tests/test_un_lock.c, server/tests/test_validate_config.c
All tests were trying to use the same PID file, and therefore they would fail to start properly and eventually hit a timeout, outputting an error:
```
[ RUN      ] test_startstop
[ERR]: Another instance of the Netopeer2 server is running.
```
I cannot use `__FILE__` directly because that one might contain full path. There's `__builtin_strchr`, but doing this via CMake is probably a bit easier.
Also adjust the temporary file name for XML operations to be consistent.
=> tests: Enable parallel test execution

cli/commands.c
=> Switch X509_get_notAfter to get0 variant

cli/commands.c
When only NC_ENABLED_SSH defined, NC_TI_OPENSSL does not exist in
enumeration type NC_TRANSPORT_IMPL. Similarly, when only NC_ENABLED_TLS
defined, NC_TI_LIBSSH does not exist in NC_TRANSPORT_IMPL.
So we have to re-factor this code excerpt for compilation.
=> Fix for only SSH or TLS enabled

keystored/scripts/ssh-key-import.sh
Fix the following error:
```
[ERR] File "/etc/keystored/keys/ssh_host_rsa_key.pem.pub" is not a public key in PEM format.
```
ssh-keygen ignores the `-m pem` argument for the public key file. It always generates it in the openssh format.
Convert it to PEM afterwards.
`ssh-keygen` requires that the converted file has `0600` permissions (it assumes it is a private key). Restrict permissions before converting and restore them afterwards.
=> keystored: force public key in pem format

server/main.c
When creating the libyang context, disable searching for yang modules in the current working directory. Depending on where `netopeer2-server` is started, we can get surprising warnings/errors:
For example, when starting the server from `/`:
```
Reading module "ietf-yang-library".
Searching for "ietf-yang-types" in /.
Unable to get information about "initrd.img.old" file in "/" when searching for (sub)modules (No such file or directory)
Unable to get information about "vmlinuz.old" file in "/" when searching for (sub)modules (No such file or directory)
...
Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
```
In that case, the "non-exsistant" items are symlinks:
```
~# ls -lhF /initrd* /vmlinuz*
lrwxrwxrwx 1 root root 32 Aug 14 16:19 /initrd.img -> …
```
=> server: disable cwd yang search dir

CMakeModules/UseCompat.cmake, cli/commands.c, compat/compat.c, compat/compat.h.in
Refs #598
`strdupa`, `strchrnul` and reimplemented `cp` function in `cli/commands.c` without `sendfile`.
=> netopeer2 CHANGE added more compat functions

server/netconf_server.c
When deleting an enpoint, neither `nc_server_endpt_set_keepalives` nor `nc_server_ch_client_endpt_set_keepalives` are called. `rc` remains with its current value which is necessarily `SR_ERR_NOT_FOUND` (meaning "end of changes").
This causes `np2srv_tcp_keepalives` to return `SR_ERR_INTERNAL` which causes `np2srv_endpt_tcp_params_cb` to stop processing the changes and return an error. No error message is printed.
Reset the value of `rc` to fix the issue.
If one of `nc_server_ch_client_endpt_set_keepalives` or `nc_server_endpt_set_keepalives` actually failed, display an explicit error message.
=> server BUGFIX fix partial processing of tcp params changes

src/netconf.c, src/netconf_nmda.c
All sr_get_data calls use the default sysrepo timeout, NP2SRV_DATA_CHANGE_TIMEOUT is not taken into account.
Use NP2SRV_DATA_CHANGE_TIMEOUT for all sr_get_data() calls.
=> netconf BUGFIX use data change timeout for sr_get_data

src/netconf.c
When error details are set by the client application that provide the requested data, forward them to the netconf client.
Fixes: #628
=> netconf BUGFIX forward get_data errors to client

server/op_editconfig.c
Two fixes for issues in moving of `list` and `leaf-list` YANG types (#636 by @syyyr). I don't know whether the non-legacy branch also has these bugs (I have not found any tests for moves neither in `legacy`, nor in `master`).
The code wanted to deliberately ignore any `SR_MOVE_LAST` values. I think that this happened because of that C convention for adding a `FOO_LAST` items to enums to signify their largest allowed value.
I did not want to modify sysrepo for this as well, so I just added a random garbage sentinel for this.
When processing YANG list moves, the code would correctly parse the relative XPath in the `edit_get_move()`, but before it could be consumed via `np2srv_sr_move_item`, it got reset when the main iteration loop processes the next change item. As a result, a relative …
=> Fix list and leaf-list moves

scripts/setup.sh
When installing yang modules add DESTDIR prefix to the NP2_MODULE_DIR.
Fixes #648
Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>
=> script.sh: take DESTDIR into account

cli/commands.c
Normal get function is deprecated as of OpenSSL 1.1.
=> commands: switch to X509_get0_notAfter

src/main.c
Fixes #654 
This is an attempt to fix following  `<error-tag>` values which were reported as `operation-failed` but shall be more specific:
- `<lock-denied>`
- `<in-use>`
- `<data-exist>`
The proposed solution here is based on the initial fix 2bd857b - to parse the message parameter in np2srv_err_sr().
There might be many more error-tags missing, though, which needs to be added case-by-case. 
IMO, more SR_ERR_XXX values for each error-tag use case would be easier to handle, though.
=> fixed several <error-tags> (issue#654)

scripts/merge_config.sh, scripts/merge_hostkey.sh, scripts/setup.sh
In my dev environment, there is no sysrepoctl or sysrepocfg in `PATH`. I usually have two versions of the netconf stack installed (at the same time): one with sanitizers and one without, so the scripts wouldn't know which binary to use (and they are usually incompatible). I added an env var override for sysrepoctl and sysrepocfg.
Also, feel free to (completely) change the commit message if you want, I'm not sure if I got that right.
Thanks
=> build FEATURE add env var sysrepo tools override

src/netconf_server_ssh.c
Running Netopeer2 as a normal user is a good use-case for testing.
In my test, I try to get all data available (with a `/*` filter). through sysrepo, but this callback errored out, when root access wasn't available.
cc @jktjkt
=> Ignore key reading failure if not running as root

src/netconf_acm.c
Hi, in our CI, this error came up
```
=================================================================
==2083==ERROR: AddressSanitizer: odr-violation (0x000000e7bc00):
[1] size=96 'nacm' /home/ci/src/cesnet-gerrit-public/CzechLight/dependencies/libyang/src/extensions/nacm.c:157:26
[2] size=88 'nacm' /home/ci/src/cesnet-gerrit-public/CzechLight/dependencies/Netopeer2/src/netconf_acm.c:31:13
These globals were registered at these points:
[1]:
#0 0x436418 in __asan_register_globals.part.0 (/home/ci/target/bin/netopeer2-server+0x436418)
#1 0x7f9a53a49ebb in asan.module_ctor (/home/ci/target/lib64/libyang1/extensions/nacm.so+0x2ebb)
[2]:
#0 0x436418 in __asan_register_globals.part.0 (/home/ci/target/bin/netopeer2-server+0x436418)
#1 0x5357ae in asan.module_ctor …
```
=> Fix odr-violation

src/log.c
Print src and fmt in case of memory shortage to have at least something (__FILE__,__LINE__ always prints log.c:49)
=> Shorten UNKNWON to UNK to avoid buffer overflow

CMakeLists.txt, src/config.h.in, src/netconf_server_ssh.c
Our appliance uses a read-only rootfs, and we're therefore managing the users' SSH pubkeys within a config-only partition. That's outside of their individual home directories.
Cc: #811
=> Compile-time options for specifying custom paths of authorized_keys

src/main.c, src/netconf.c, src/netconf_nmda.c
Refs #818
The server will not crash due to username getter function.
However, the internal error still remains unresolved.
=> netconf BUGFIX server crash protection

src/netconf.c
Callback functions ignore the SR_EV_ABORT event.
=> netconf BUGFIX Clb func ignore the ABORT event 

src/netconf_acm.c, src/netconf_acm.h, src/yang_push.c
Before groups were collected for each node which could cause timeouts if
user was in a large number of groups. Rewrite so that it is called once
per operation.
Refs #998
=> netconf acm MAINTANANCE improve performance of group collection

CMakeLists.txt, README.md
There's no need to skip testing for release builds. On the contrary, given that the release build is something that the end users will run, it makes sense to test the release builds as well.
=> misc Ci fixes

tests/test_parallel_sessions.c
```
Netopeer2/tests/test_parallel_sessions.c:81:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
asprintf(&path, "%s/%s/%s", NP_SR_REPOS_DIR, st->test_name, NP_LOG_FILE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/f1r94qx7a8m8iz7fxvlq655gbawql7xf-glibc-2.33-50-dev/include/bits/stdio2.h:207:3: note: expanded from macro 'asprintf'
__asprintf_chk (ptr, __USE_FORTIFY_LEVEL - 1, __VA_ARGS__)
^~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
Fixes: 8c6e102 test FEATURE print np2 log on unexpected reply
=> tests: check asprintf()'s results

tests/CMakeLists.txt
CMake is a generator which can be used with other tools than just `make` -- `ninja` is a good candidate which tends to build a little faster. It's therefore a bug to try invoking `make` on some target directly.
See-also: https://github.com/sysrepo/sysrepo/pull/2647
Fixes: e70b9c9 tests UPDATE cleanup SHM files after tests
=> Fix build when not using CMake's make generator

tests/np_test.h, tests/test_filter.c
This adds a `get-data` subtree filter test on the `operational` datastore.  At this point the test fails because none of the data is being returned by the `get-data` request.   Removing the values form the subtree filter will allow some data to be retrieved so I think the test is correct, just that the filtering is not working correctly.
=> Added get-data operational test filter

tests/np_test.h
When running tests via ctest, setup failure messages are not shown for
some reason (they are shown when running the test directly). Fix this by
changing the macro to print to stderr.
=> Fix setup error printing

src/common.c, src/common.h, src/main.c
Hi,
@roytak implemented pam usage for the netconf2 lib. (https://github.com/CESNET/libnetconf2/pull/382).
But it seems there is no way to use it without patching the source of either netconf2 or dependent tools like netopeer2.
So I add the command line option for the netopeer2 server to make it usable without add the name/dir to the sources.
=> add commandline option to set PAM Module Name/DIR used for interactive ssh authentication

src/netconf_confirmed_commit.c
Hi!
My expectation is that after the confirming commit is issued, backup files (a bunch of jsons and meta file in `/var/netopeer2/confirmed_commit/`) should be cleaned. I observe they are kept and after the server restarts it rollbacks the changes even the confirming commit was successful. 
I made a fix according to my understanding, please check.
=> ncc BUGFIX Clean backup dir properly after successful commit

doc/netopeer2-server.8, src/main.c
This patch adds support for running `netopeer2-server` under init systems like [Finit](https://github.com/troglobit/finit/), which supervise processes running in the foreground.  Similar to `-d`, but still using syslog.
=> Add support for running netopeer2-server in foreground with syslog

tests/CMakeLists.txt
As per the docs, the SIGEV_THREAD sigevent option instructs the kernel to create a thread in this process when that timer expires (in fact this is done by the C library, and the kernel "just" wakes up that thread AFAICT). However, this newly created thread appears to have completely bypassed TSAN, and when the just-created thread hits any TSAN interceptor which assumes that some per-thread TSAN structures have been already set up, the application segfaults (for example like this):
```
#0  0x00005555556192d4 in __tsan::user_alloc_internal(__tsan::ThreadState*, unsigned long, unsigned long, unsigned long, bool) ()
#1  0x00005555556196a4 in __tsan::user_alloc(__tsan::ThreadState*, unsigned long, unsigned long) ()
#2  0x00005555555d3db5 in malloc ()
#3  0x00007ffff7889470 in …
```
=> tests: `SIGEV_THREAD` doesn't work under TSAN

modules/ietf-subscribed-notif-receivers.yang, modules/ietf-udp-client.yang, modules/ietf-udp-notif-transport.yang, modules/ietf-udp-notif.yang, scripts/setup.sh
Hello,
This is the first part of the configured subscription integration.
Enable the configured feature in setup.sh.
Add the new yang files to setup.sh.
Add the yang files to the project with TLS disabled.
Direct definition of the receiver in the subscription is disabled. Only reference receiver instances is enabled.
This avoids this warning:
root@ubuntu2204:~/sshfs_root# netopeer2-cli 
> connect -u
ly WARNING: Schema node "transport" for parent "/ietf-subscribed-notifications:subscriptions/subscription" not found; in expr "derived-from(../../transport" with context node "/ietf-subscribed-notifications:subscriptions/subscription/receivers/receiver".
=> Configured subscription integration

CMakeLists.txt
cmake: don't hard-code absolute path name `/etc`
- this breaks packaging and installation into a prefix in general
- there's a [`GNUInstallDirs` variable for `/etc`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), too
Also, don't make this installation conditional on the existence of `/etc`. Whether or not that directory exists on a build system has no meaning for installation to a target system. This had a potential to break cross-compiling.
=> cmake: don't hard-code absolute path name /etc

tests/CMakeLists.txt, tests/np2_test_config.h.in, tests/scripts/kill_np_server.sh.in
I started getting failures because these paths are now "too long". It used to work fine as far as I can recall, so let's shave off a few bytes from these paths, and hope for the best.
=> tests: shorten path to the UNIX socket

cli/README.md, cli/commands.c, cli/completion.c, cli/configuration.c, cli/doc/netopeer2-cli.1
CRLs are now obtainable only through a x509 extension.
Fixes #1597
=> Remove netopeer2-cli's CRL from a file support

distro/pkg/rpm/netopeer2.spec
On Almalinux9 (and probably other RHEL9 like systems) the "apkg build" packaging step for RPMs seems broken.
I'm not sure, what realy happen but some suggestions. 
The cmake file install/copies a file with the line
``` install(FILES "${CMAKE_SOURCE_DIR}/pam/netopeer2.conf" DESTINATION "${CMAKE_INSTALL_SYSCONFDIR}/pam.d")``` 
`CMAKE_INSTALL_SYSCONFDIR` is set to "etc" by default, what looks to be correct.
However, maybe related to [cmake GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#special-cases) and and a set/default `CMAKE_INSTALL_PREFIX` it's expanded internal to `/usr/etc`, resulting the file mentioned above is put to `.../usr/etc/pam.d/`
The RPM Spec file on the other side, expect it in `%{_sysconfdir}` aka  `/etc` and fails. 
A solution is to set …
=> Fix apkg rpm build

src/err_netconf.c, src/err_netconf.h, src/main.c, src/netconf.c, tests/CMakeLists.txt, tests/np2_other_client.c, tests/np2_other_client.h, tests/np2_test.c, tests/np2_test.h, tests/test_candidate.c, tests/test_confirmed_commit.c, tests/test_edit.c, tests/test_error.c, tests/test_filter.c, tests/test_nacm.c, tests/test_other_client.c, tests/test_parallel_sessions.c, tests/test_rpc.c, tests/test_sub_ntf.c, tests/test_sub_ntf_advanced.c, tests/test_sub_ntf_filter.c, tests/test_subscribe_filter.c, tests/test_subscribe_param.c, tests/test_url.c, tests/test_with_defaults.c, tests/test_yang_push.c, tests/test_yang_push_advanced.c
The last partial solution for CESNET/netopeer2#1556.
=> NETCONF error tags

CMakeLists.txt, src/config.h.in
Since the commit in the link, some performance issues could be observed. Make the thread count and sleep times configurable to avoid this.
Link: https://github.com/CESNET/netopeer2/commit/5391a73bf27b4878f981bf8a474e206cd2d212c3
=> server UPDATE make thread and poll configurable

modules/ietf-notification-capabilities@2022-02-17.yang, modules/ietf-system-capabilities@2022-02-17.yang, scripts/common.sh, src/common.c, src/common.h, src/main.c, src/netconf_subscribed_notifications.c
This patch is an implementation of RFC9696
Link: https://datatracker.ietf.org/doc/html/rfc9196
netopeer2 can return the operational data of /ietf-system-capabilities:system-capabilities
which contains the limit values of several parameters.
max-nodes-per-update: there is no limit on the number of node to send inside a notif in sysrepo. The max unsigned integer value is set.
periodic-notifications-supported and on-change-supported: The publisher is capable of sending notifications for 'config false' and 'config true' nodes.
minimum-update-period and minimum-dampening-period: The minimum value is 0.
supported-excluded-change-type: All types of changes can be excluded.
A sysrepocfg command would give this result:
`# sysrepocfg -f json -x "/ietf-system-capabilities:system-capabilities" -v2 -X …
=> implement ietf-system-capabilities and ietf-notification-capabilities
