server/main.c

Signed-off-by: Mislav Novakovic <mislav.novakovic@sartura.hr>

travis BUGFIX wrap header in DEBUG macro

---

server/op_notifications.c

Hi,
I found that  notification with nested data node could not be sent by server, and then try to fix it.

server BUGFIX failed to handle notification with nested data node

---

server/op_generic.c
server/operations.c

Hi,
This request is to make the `anyxml`/`anydata` node be created correctly.

server CHANGE support anyxml/anydata in rpc output and notification

---

server/op_copyconfig.c
server/tests/test_copy_config.c

Hi,
this is the pull request for the fix of issue https://github.com/CESNET/Netopeer2/issues/242.
Sorry for the late reaction - I was on vacation.
Regards,
Peter

Copy config solution

---

server/tests/test_edit_get_config.c

This is a unit test to add test coverage for the use case in #267. It tests a selection node subtree filter whose node is a key.

Unit test for selection node filter on key

---

server/operations.c
server/tests/test_notif.c

This commit fixes the scenario in which the server needs to report a list without keys. (This is valid for lists that do not represent configuration; see [RFC 7950 section 7.8.2.](https://tools.ietf.org/html/rfc7950#section-7.8.2)) This scenario was broken by the changes in e75e339, which caused `op_sr2ly()` to fail if the list's xpath predicate did not contain a `child="value"` expression.
I made two modifications to `op_sr2ly_parse_pred()`:
1. Fix the loop that searches for `'='` so that it stops at the NULL termination of the string if no `'='` has yet been found. (The existing code could search far beyond the bounds of the string, sometimes resulting in a segmentation fault.)
2. Distinguish between a failure to find a `child="value"` predicate, which is a valid case, and other general …

Fix list without key

---

server/main.c

API changes for https://github.com/CESNET/libyang/pull/602

Adapt to CESNET/libyang#602

---

server/op_copyconfig.c
server/operations.c
server/tests/CMakeLists.txt
server/tests/test_copy_config.c

- Need WITHSIBLINGS, output only had one module included
- Was copying config=false nodes

Fix two errors in <copy-config> to URL

---

modules/ietf-yang-library.yang

Update ietf-yang-library to revision 2019-01-04

---

keystored/scripts/ssh-key-import.sh

Fix shell error for undefined variable.
Fix running the script again after setting KEYSTORED_CHECK_SSH_KEY=0.

keystored: ssh-key-import.sh improvements

---

src/netconf_server.c
src/netconf_server_ssh.c

When changing the configuration to add new listen endpoints, if one of these endpoints specifies an invalid parameter (for example, a "local-address" which is not present on any interface on the system), the nc_server_endpt_set_address() function will return an error (since the socket cannot be created).
If such errors occur, do not abort the processing of changes since other endpoint address/port may be valid and should be configured. Otherwise, these changes are lost and will never be configured.
If one error occurred, return an error to notify the sysrepo client which applied the configuration that something went wrong.
Signed-off-by: Robin Jarry <robin.jarry@6wind.com>

server BUGFIX do not abort endpoint changes processing on error

---

src/main.c

Hi, now that there options for separating the sysrepo repository and shm prefix via environmental variables, the only thing that disallows launching more netopeer2 processes is the pidfile. This PR adds on option to set a custom pid file.

Add option for setting PID

---

src/netconf_acm.c

Precondition:
- A RADIUS server with the corresponding shared-secret has been configured.
- The following NACM rules have been configured:
```xml
<nacm:nacm xmlns:nacm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
<nacm:rule-list>
<nacm:name>EXAMPLE</nacm:name>
<nacm:group>EXAMPLE</nacm:group>
<nacm:rule>
<nacm:name>denyRadiusSecret</nacm:name>
<nacm:action>deny</nacm:action>
<nacm:path xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system">/sys:system/sys:radius/sys:server/sys:udp/sys:shared-secret</nacm:path>
</nacm:rule>
<nacm:rule>
<nacm:name>denyRadiusSecret</nacm:name>
<nacm:access-operations>read</nacm:access-operations>
<nacm:action>permit</nacm:action>
<nacm:path xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system">/sys:system/sys:r …
```

Consideration of partial matching NACM rules corrected.

---

src/common.c
src/common.h
src/main.c
src/netconf.c
src/netconf_nmda.c

see [CESNET/netopeer2#901](https://github.com/CESNET/netopeer2/issues/901)

keep track of NC-sessions-SR-session associations

---

tests/np_test.c
tests/np_test.h
tests/test_rpc.c

Create test for some basic RPCs.
Cancel test currently segfaults.

Tests libyang2

---

distro/pkg/rpm/netopeer2.spec
distro/scripts/upstream-version.sh

Fedora review: https://bugzilla.redhat.com/show_bug.cgi?id=2088450

distro UPDATE rpm packaging from Fedora review

---

distro/pkg/rpm/netopeer2.spec

Fedora review finally finished: https://bugzilla.redhat.com/show_bug.cgi?id=2088450

rpm UPDATE packaging from Fedora

---

src/netconf_nmda.c

Fix https://github.com/CESNET/netopeer2/commit/c27a561b55e72fd3c6414b259ee652572553b65d (libyang1 branch) is missing in devel

nmda BUGFIX always discard changes after edit

---

src/netconf_server_ssh.c

Hi,
if `NP2SRV_SSH_AUTHORIZED_KEYS_ARG_IS_USERNAME` is set, then there is no need that the netopeer client is a system user. But the current version fails, if the user does not exist in the user database. 
This PR skips that, if NP2SRV_SSH_AUTHORIZED_KEYS_ARG_IS_USERNAME is set. 
Kind regards
Henning

pubkey authentication for non system user

---

CMakeLists.txt
patches/0001-feat-add-local-address-to-sender.patch

Hello,
This time, add udp notification code from https://github.com/network-analytics/udp-notif-c-collector.
Build the code with the rest of the project.
Best regards
Jeremie

Configured subscription integration

---

src/netconf.c

NACM should be applied. Setting the config variable applies only to url upload.

netconf BUGFIX copy-config data upload for url

---

tests/test_candidate.c
tests/test_confirmed_commit.c
tests/test_edit.c
tests/test_filter.c
tests/test_nacm.c
tests/test_parallel_sessions.c
tests/test_sub_ntf.c
tests/test_sub_ntf_advanced.c
tests/test_sub_ntf_filter.c
tests/test_subscribe_filter.c
tests/test_subscribe_param.c
tests/test_url.c
tests/test_with_defaults.c
tests/test_yang_push.c
tests/test_yang_push_advanced.c

It is a same issue as in sysrepo/sysrepo#3065

tests REFACTOR added missing stdint.h

---

distro/pkg/rpm/netopeer2.spec

Move SERVER_DIR to /var/lib in rpm
